name       : libpgm
version    : 5.3.128
release    : 4
source     :
    - https://github.com/steve-o/openpgm/archive/refs/tags/release-5-3-128.tar.gz : 8d707ef8dda45f4a7bc91016d7f2fed6a418637185d76c7ab30b306499c6d393
license    : LGPL-2.1
component  : programming.library
summary    : OpenPGM - implementation of the Pragmatic General Multicast (PGM, RFC3208)
description: |
    OpenPGM - implementation of the Pragmatic General Multicast (PGM, RFC3208)
setup      : |
    cd $workdir/openpgm/pgm/

    # 5.3.128 is a _little_ broken
    2to3 -wn version_generator.py
    cp openpgm-5.2.pc.in openpgm-5.3.pc.in

    ./bootstrap.sh
    %configure --disable-static
build      : |
    cd $workdir/openpgm/pgm/
    %make
install    : |
    cd $workdir/openpgm/pgm/
    %make_install
