name       : libpgm
version    : 5.2.122
release    : 1
source     :
    - https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/openpgm/libpgm-5.2.122.tar.gz : 6b895f550b95284dcde7189b01e04a9a1c1f94579af31b1eebd32c2207a1ba2c
license    : LGPL-2.1
component  : programming.library
summary    : OpenPGM - implementation of the Pragmatic General Multicast (PGM, RFC3208)
description: |
    OpenPGM - implementation of the Pragmatic General Multicast (PGM, RFC3208)
setup      : |
    cd $workdir/openpgm/pgm/
    %configure --disable-static
build      : |
    cd $workdir/openpgm/pgm/
    %make
install    : |
    cd $workdir/openpgm/pgm/
    %make_install
